ALTER TABLE tracks ADD COLUMN IF NOT EXISTS s3_key VARCHAR(1024);
ALTER TABLE tracks ADD COLUMN IF NOT EXISTS content_type VARCHAR(255);
ALTER TABLE tracks ADD COLUMN IF NOT EXISTS size_bytes BIGINT;
ALTER TABLE tracks ADD COLUMN IF NOT EXISTS etag VARCHAR(255);
ALTER TABLE tracks ADD COLUMN IF NOT EXISTS duration INTEGER;